logging:
  level:
     org:
       springframework:
         security: DEBUG
         
server:
  port: 8282
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: South_East_Asia
  environment: Dev
      