server:
  contextPath: /api/dev
  error:
    include-stacktrace: NEVER
  port: 0
---
spring:
    profiles: dev
    data:
      mongodb:
        host: localhost
        port: 27017
        database: nexstore
        repositories:
          enabled: true
    jackson:
      serialization:
        write-dates-as-timestamps: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: localhost