server:
  contextPath: /api/dev
  port: 9090
  error:
    include-stacktrace: NEVER
---
spring:
    profiles: dev
    data:
      mongodb:
        host: localhost
        port: 27017
        database: nexstore
        repositories:
          enabled: true
          
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: localhost