server:
  contextPath: /api/dev
---
spring:
    profiles: dev
    data:
      mongodb:
        host: localhost
        port: 27017
        database: nexstore
        repositories:
          enabled: true
---
environment: dev
---
spring:
  application:
    name: CustomerRegistration